/*
 * Microgateway management API
 *
 * # Introduction This is the management API for Swift Microgateway (MGW). It allows you remotely manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorCode {
    #[serde(rename = "error_code")]
    pub error_code: ErrorCodeEnum,
    #[serde(rename = "error_description")]
    pub error_description: String,
}

impl ErrorCode {
    pub fn new(error_code: ErrorCodeEnum, error_description: String) -> ErrorCode {
        ErrorCode { error_code, error_description }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCodeEnum {
    #[serde(rename = "MGW")]
    Mgw,
    #[serde(rename = "MGW_Configuration")]
    MgwConfiguration,
}

impl Default for ErrorCodeEnum {
    fn default() -> ErrorCodeEnum {
        Self::Mgw
    }
}
