/*
 * Microgateway management API
 *
 * # Introduction This is the management API for Swift Microgateway (MGW). It allows you remotely manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JarVerificationEntity {
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "valid")]
    pub valid: bool,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "warnings")]
    pub warnings: String,
}

impl JarVerificationEntity {
    pub fn new(file_name: String, valid: bool, reason: String, warnings: String) -> JarVerificationEntity {
        JarVerificationEntity { file_name, valid, reason, warnings }
    }
}
