/*
 * Microgateway management API
 *
 * # Introduction This is the management API for Swift Microgateway (MGW). It allows you remotely manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalSignEntity {
    #[serde(rename = "jws")]
    pub jws: String,
    #[serde(rename = "header")]
    pub header: serde_json::Value,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
}

impl LocalSignEntity {
    pub fn new(jws: String, header: serde_json::Value, payload: serde_json::Value) -> LocalSignEntity {
        LocalSignEntity { jws, header, payload }
    }
}
