/*
 * Microgateway management API
 *
 * # Introduction This is the management API for Swift Microgateway (MGW). It allows you remotely manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

/// SagEntity : SAG host & port

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SagEntity {
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "port")]
    pub port: i32,
}

impl SagEntity {
    /// SAG host & port
    pub fn new(hostname: String, port: i32) -> SagEntity {
        SagEntity { hostname, port }
    }
}
