[package]
name = "mgwconf-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "^0.1" }
anyhow = "1.0"
log = "0.4"
inquire = "0.6.1"
clap = "4.2.5"

mgwconf-network = { path = "../mgwconf-network", features = ["cli"] }
mgwconf-vault = { path = "../mgwconf-vault" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = { version = "0.2" }
