[package]
name = "mgwconf-vault"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cbc = "0.1.2"
aes = "0.8"
base64 = "0.21"
rand = "0.8.5"
log = "0.4"
hex = "0.4.3"
rust-argon2 = "2.0"
zeroize = { version = "1.7.0", features = ["zeroize_derive"] }