/*
 * Microgateway management API
 *
 * # Introduction This is the management API for Swift Microgateway (MGW). It allows you remotely manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdatedOasInfo : Returns number of created and deleted OAS

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatedOasInfo {
    #[serde(rename = "numberOfNewOAS")]
    pub number_of_new_oas: i32,
    #[serde(rename = "numberOfDeletedOAS")]
    pub number_of_deleted_oas: i32,
}

impl UpdatedOasInfo {
    /// Returns number of created and deleted OAS
    pub fn new(number_of_new_oas: i32, number_of_deleted_oas: i32) -> UpdatedOasInfo {
        UpdatedOasInfo {
            number_of_new_oas,
            number_of_deleted_oas,
        }
    }
}
