hosts:
  - '127.0.0.1:9004'

commands:
  - type: Create
    entity_type: Certificate
    json: |
      {
        "alias": "test",
        "certificateX509": "-----BEGIN CERTIFICATE-----\nMIIDbzCCAlegAwIBAgIUSlLCzSolNnq6tOPx/3r2PB9Bu+YwDQYJKoZIhvcNAQEL\nBQAwRTELMAkGA1UEBhMCRlIxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM\nGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMjExMDUxOTEyNDRaFw0zMjEx\nMDIxOTEyNDRaMEUxCzAJBgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw\nHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB\nAQUAA4IBDwAwggEKAoIBAQCvP1Y3s2k8QvI5xXHb8R8iYo821SDGo2NS+OB4aMy7\nG+8u398sghEjeuoUUmTB5/LXt6E2d/xoXQCHlwxCnMFKIUCARN5SrVYVEHAXX7Wm\n2Q5yoLJ5lXhx6Rl3Ly4qwUpBvmdc9FxxgSbtxjcL4s2be7FNNk9WcakTRf31RBQM\nW+taHL12xcO8i4cSd27xk/8Rufi9AEBe2B7iKOjHkdmf4OZAFLoUWGw9g9EV89Aq\nF4iVY6V9s3GwZXE/V/1yxO0CvaljU1kNdKCFc9OZxoQsdJexD+2E0I7Uc2kBZk9C\nCm201u69fHsCn4R+3iPiESaMc2L9aBKzXB1ai5DtfEyFAgMBAAGjVzBVMB8GA1Ud\nIwQYMBaAFO1ws6mVtk/0R4nAJY1lrfgpcNZ9MAkGA1UdEwQCMAAwCwYDVR0PBAQD\nAgTwMBoGA1UdEQQTMBGCCWxvY2FsaG9zdIcEfwAAATANBgkqhkiG9w0BAQsFAAOC\nAQEAozeAaPvaPHIELd3PC5LaHa5EekZRRRk6094fe01kvTsePLNJXtUb3sMSUAaJ\nunMLnM7LVkPRPjraJl1SzzILXNCwtGdsciL6bICxJ6Gft9sPnl2fEc5oiXqJA/KU\n+9GUPN0ChjcWhS1J6a88PMSLBe1W5XDdhiu07xlderN6HiMVHyA5OiUjltVylfBn\nduuTiqzixDr1w8MdcgSQ2J53Lkp2flFvWeW438o4x9w11LY/2Sr1wwWEppk2Qxao\nN3DPVWtHYQcAC2M3X06zkPqxtGGqnSe/u7iekfwYXPM4Qi0ZDRehmoOUXrrkDHkb\nVAdAkpYChCt7ltnTtr6Z1PnIJw==\n-----END CERTIFICATE-----"
      }
  - type: Create
    entity_type: Sag
    json: |
      {
        "hostname": "test2",
        "port": 48002,
        "messagePartnerName":"Sag MP",
        "lauKey": "Abcd1234Abcd1234Abcd1234Abcd1234",
        "sslDN": "ssl",
        "userDNs":
          [
            "cn=apitest,ou=apicore,o=swhqbebb,o=swift"
          ],
        "active": true,
        "publicCertificateAlias": "test"
      }
  - type: Create
    entity_type: BusinessApplication
    json: |
      {
        "applicationName": "BO1",
        "sharedSecret": "Abcd1234Abcd1234Abcd1234Abcd1234"
      }
  - type: Create
    entity_type: Profile
    json: |
      {
        "applicationName": "BO1",
        "profileName": "trackerProfile",
        "rbacScope": "swift.apitracker!p",
        "userDNs": [
          "cn=diana-milevsa,ou=dmilevsk,o=swhqbebb,o=swift"
        ]
      }
  - type: Create
    entity_type: Proxy
    json: |
      {
        "hostname": "test",
        "port": 9005,
        "user": "fptest",
        "password": "fptest"
      }
  - type: Create
    entity_type: ApiClientCredential
    json: |
      {
        "applicationName": "BO1",
        "consumerKey": "JBrAF6pKG2tWq00Cm2QTQ76ywHsqyaxG",
        "consumerSecret": "31tnoYAxLR5dqx0Q"
      }