/*
 * Microgateway configuration API
 *
 * # Introduction This is the configuration API for Swift Microgateway (MGW). It allows remotly configure Microgateway. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway configuration API and how to integrate the use of the MGW within their organisation   * Software developers using the API to configure MGW
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorDefaultResponse {
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<serde_json::Value>>,
}

impl ErrorDefaultResponse {
    pub fn new(
        timestamp: i32,
        status: i32,
        error: String,
        message: String,
        path: String,
    ) -> ErrorDefaultResponse {
        ErrorDefaultResponse {
            timestamp,
            status,
            error,
            message,
            path,
            errors: None,
        }
    }
}
