/*
 * Microgateway monitoring API
 *
 * # Introduction This is the monitoring API for Swift Microgateway (MGW). It allows you remotly manage and control a bunch of Microgateway services API as SAG, etc. # Authentication Use API Key shared between Business Application and Microgateway. # Audience:    * Business analysts and architects to understand the functionality of the Microgateway management API and how to integrate the use of the MGW within their organisation   * Software developers/SAG managers using the API to manage MGW service's
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developer@swift.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorDefaultResponse {
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl ErrorDefaultResponse {
    pub fn new(
        timestamp: i32,
        status: i32,
        error: String,
        message: String,
        path: String,
    ) -> ErrorDefaultResponse {
        ErrorDefaultResponse {
            timestamp,
            status,
            error,
            message,
            path,
        }
    }
}
