name: MGWC ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Run Just Default
        run: just default

      - name: Build
        id: build
        run: |
          just build-ci
