name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Test
        run: cargo test --release
      - name: Build
        run: just --set target "x86_64-pc-windows-msvc" release
      - name: Upload artifact mgwc.exe
        uses: actions/upload-artifact@v4
        with:
          name: mgwc.exe
          path: ./target/x86_64-pc-windows-msvc/release/mgwc.exe
      - name: Upload artifact mgwc_ui.exe
        uses: actions/upload-artifact@v4
        with:
          name: mgwc_ui.exe
          path: ./target/x86_64-pc-windows-msvc/release/mgwc_ui.exe
        
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Test
        run: cargo test --release
      - name: Build
        run: just --set target "x86_64-unknown-linux-gnu" release
      - name: Upload artifact mgwc.exe
        uses: actions/upload-artifact@v4
        with:
          name: mgwc.exe
          path: ./target/x86_64-unknown-linux-gnu/release/mgwc
      - name: Upload artifact mgwc_ui.exe
        uses: actions/upload-artifact@v4
        with:
          name: mgwc_ui.exe
          path: ./target/x86_64-unknown-linux-gnu/release/mgwc_ui