name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build mgwc
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --target x86_64-unknown-linux-gnu:centos --features=cli --bin="mgwc"
    - name: Build mgwc_ui
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --target x86_64-unknown-linux-gnu:centos --features=ui --bin="mgwc_ui"
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: mgwc
        path: target/release/mgwc
    - uses: actions/upload-artifact@v3
      with:
        name: mgwc_ui
        path: target/release/mgwc_ui
    
